name: Nextbillion Asset Tracking SDK Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.1"

      - name: Install dependencies
        run: flutter pub get
    
      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run analyzer
        run: flutter analyze lib

      - name: Run tests with coverage
        run: |
          flutter test --coverage  