name: Lint Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  dart-lint:
    name: Dart/Flutter Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Run Dart analyzer
      run: flutter analyze
    
    - name: Run Dart format check
      run: dart format --set-exit-if-changed .
    
    - name: Check for force cast issues
      run: |
        echo "Checking for force cast issues..."
        flutter analyze | grep -i "force cast" || echo "No force cast issues found"
    
    - name: Run tests
      run: flutter test

  kotlin-lint:
    name: Kotlin Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Make gradlew executable
      run: |
        chmod +x android/gradlew || echo "gradlew not found in main project"
        chmod +x example/android/gradlew || echo "gradlew not found in example project"
    
    - name: Format Kotlin code (main project)
      run: |
        cd android
        ./gradlew ktlintFormat || echo "Some formatting issues could not be auto-fixed"
      continue-on-error: true
    
    - name: Format Kotlin code (example project)
      run: |
        cd example/android
        ./gradlew ktlintFormat || echo "Some formatting issues could not be auto-fixed"
      continue-on-error: true
    
    - name: Run ktlint on main project
      run: |
        cd android
        ./gradlew ktlintCheck || echo "Kotlin lint warnings found (package-name rule for Flutter plugins)"
      continue-on-error: true
    
    - name: Run ktlint on example project
      run: |
        cd example/android
        ./gradlew ktlintCheck || echo "Kotlin lint warnings found (package-name rule for Flutter plugins)"
      continue-on-error: true

  ios-lint:
    name: iOS Lint
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Verify iOS directory structure
      run: |
        ls -la example/ios/
        echo "Checking for Podfile..."
        test -f example/ios/Podfile && echo "Podfile found" || echo "Podfile not found"
    
    - name: Run iOS lint
      run: |
        pwd
        ls -la
        echo "=== Environment Information ==="
        echo "Xcode version:"
        xcodebuild -version
        echo "macOS version:"
        sw_vers
        echo "=== Navigating to example/ios... ==="
        cd example/ios
        pwd
        ls -la
        echo "=== Running pod install... ==="
        pod install
        echo "=== Pod install completed, checking Podfile.lock ==="
        cat Podfile.lock | grep -A 5 -B 5 "DEPLOYMENT_TARGET" || echo "No deployment target info in Podfile.lock"
        echo "=== Running xcodebuild with code signing disabled... ==="
        set -e
        xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Debug clean build \
          -allowProvisioningUpdates \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          DEVELOPMENT_TEAM="" \
          PROVISIONING_PROFILE="" 2>&1 | tee xcodebuild.log
        echo "=== Build exit code: $? ==="